import type { ErrorType } from '../types/error.types';

/** Separator between the segments of a generated error key. */
const KEY_SEGMENT_SEPARATOR = '.';

/**
 * Build the deterministic fallback key of an error from its identifying triplet.
 *
 * Every error stored by the error handler needs a `key`: the UI only offers a
 * dismiss button for errors that have one, and `clearByKey` is the only way to
 * remove a single error again. Callers that report a one-off problem (a failed
 * fetch, a blocked cross-origin request) have no natural key to pass, so the
 * store falls back to this value.
 *
 * The result is stable for a given error source — the same `component` /
 * `action` / `type` triplet always produces the same key — which is what makes
 * "clear my own previous errors" (`clearByKey`) and deduplication possible.
 *
 * @param component - Name of the component where the error occurred
 * @param action - Action/operation during which the error occurred
 * @param type - Type of the error
 * @returns The generated key, e.g. `ApiResourcesStore.fetchData.api`
 *
 * @example
 * ```typescript
 * buildFallbackErrorKey('ApiResourcesStore', 'fetchData', 'api');
 * // → 'ApiResourcesStore.fetchData.api'
 * ```
 */
export const buildFallbackErrorKey = (component: string, action: string, type: ErrorType): string =>
    [component, action, type].join(KEY_SEGMENT_SEPARATOR);

/**
 * Whether an error's key was generated by {@link buildFallbackErrorKey} rather
 * than supplied by the caller.
 *
 * A caller-supplied key names something meaningful to the user (the config key
 * or column that failed), while a generated one only repeats the component and
 * type that are already displayed. The error UI uses this to decide whether the
 * key is worth showing.
 *
 * @param error - The error's identifying fields
 * @returns `true` if the key equals the generated fallback
 */
export const isFallbackErrorKey = (error: {
    component: string;
    action: string;
    type: ErrorType;
    key?: string;
}): boolean => error.key === buildFallbackErrorKey(error.component, error.action, error.type);
