import { defineComponent, h, ref, onMounted, onBeforeUnmount } from 'vue';
import { isExternalUrl } from '../../../../lib/api';
import { useExistingCoreStore } from '../../../../state';
import { DEFAULT_STORE_ID } from '../../../../lib/default-values.lib';

const MODAL_ID = 'destroyModal';
const MODAL_LABEL_ID = 'destroyModalLabel';

/**
 * Submits a DELETE request to the given route URL via a dynamically created form.
 *
 * Creates a hidden `<form method="POST">` with:
 * - `_method=DELETE` hidden field (HTTP method override for framework routers)
 * - `_token` hidden field from `<meta name="csrf-token">` if present (best-effort CSRF protection)
 *
 * The form is appended to `document.body`, submitted, then removed from the DOM.
 *
 * Security gate: if `route` is cross-origin (points to a different origin than the
 * current page), the submit is blocked entirely. The `data-route` value comes from the
 * API response / preprocessor, so a tampered response could redirect the POST to a
 * foreign origin — and thereby leak the `<meta name="csrf-token">` content.
 * Same-origin destroy is the normal (Laravel session + CSRF) flow; cross-origin
 * destroy has no legitimate use case, so it is blocked (not just stripped of the token).
 *
 * The block is NOT written to the console (per the original plan, the plugin does not
 * log to the console) — the caller can signal it via an `onBlocked` callback into the
 * central error store, which shows a visible banner even with `drop_console` in
 * production. This way the module-level (pure, testable) function does not depend on
 * the store.
 *
 * @param route - The fully resolved destroy URL (from `data-route` on the modal trigger)
 * @param onBlocked - Optional callback invoked with the route when a cross-origin submit is blocked
 */
function submitDestroyForm(route: string, onBlocked?: (route: string) => void): void {
    if (isExternalUrl(route)) {
        onBlocked?.(route);
        return;
    }

    const form = document.createElement('form');
    form.method = 'POST';
    form.action = route;

    const methodInput = document.createElement('input');
    methodInput.type = 'hidden';
    methodInput.name = '_method';
    methodInput.value = 'DELETE';
    form.appendChild(methodInput);

    const csrfToken = document.querySelector('meta[name="csrf-token"]')?.getAttribute('content');
    if (csrfToken) {
        const tokenInput = document.createElement('input');
        tokenInput.type = 'hidden';
        tokenInput.name = '_token';
        tokenInput.value = csrfToken;
        form.appendChild(tokenInput);
    }

    document.body.appendChild(form);
    form.submit();
    document.body.removeChild(form);
}

/**
 * DestroyModal Component
 *
 * Built-in delete confirmation Bootstrap 5 modal component.
 * Always rendered at the end of the Aura wrapper (`id="destroyModal"`).
 *
 * Behavior:
 * 1. Trigger elements generated by `renderModalNode` open this modal via
 *    `data-bs-target="#destroyModal"` and `data-route="<resolved-url>"` attributes.
 * 2. The native Bootstrap `show.bs.modal` event saves the trigger element's `data-route`
 *    attribute into the `currentRoute` ref.
 * 3. Clicking the "Delete" button submits a form: `POST` + `_method=DELETE` + CSRF token (best-effort).
 * 4. CSRF: if `<meta name="csrf-token">` is found in the DOM, it is added to the form as a
 *    `_token` hidden field — otherwise omitted (the backend's own middleware handles it).
 * 5. Origin protection: the submit only runs for a same-origin `data-route`; for a
 *    cross-origin route the entire submit is blocked (a tampered response cannot leak
 *    the CSRF token to a foreign origin).
 *
 * The modal's structure and behavior are fixed, but its labels can be localized via the
 * `labels` config key (`confirmDeleteTitle`, `confirmDeleteBody`, `cancel`, `confirmDelete`).
 * For custom delete logic, the developer builds their own modal implementation with a different id.
 *
 * @example
 * ```html
 * <!-- Trigger element (generated by renderModalNode, data-route resolved by the preprocessor) -->
 * <a data-bs-toggle="modal" data-bs-target="#destroyModal" data-route="http://app.test/users/5/destroy">
 *   <i class="fas fa-trash text-danger" />
 * </a>
 * <!-- DestroyModal automatically appears asking for confirmation, then submits a POST form -->
 * ```
 */
export const DestroyModal = defineComponent({
    name: 'DestroyModal',
    props: {
        /** The table's store identifier (the source of localized labels) */
        storeId: {
            type: String,
            default: DEFAULT_STORE_ID,
        },
    },
    setup(props) {
        const core = useExistingCoreStore(props.storeId);

        const currentRoute = ref<string | null>(null);
        const modalRef = ref<HTMLElement | null>(null);

        const handleShowModal = (event: Event): void => {
            const relatedTarget = (event as Event & { relatedTarget?: Element | null })
                .relatedTarget;
            const route = relatedTarget?.getAttribute('data-route') ?? null;
            currentRoute.value = route;
        };

        onMounted(() => {
            modalRef.value?.addEventListener('show.bs.modal', handleShowModal);
        });

        onBeforeUnmount(() => {
            modalRef.value?.removeEventListener('show.bs.modal', handleShowModal);
        });

        const handleConfirm = (): void => {
            const route = currentRoute.value;
            if (!route) return;
            submitDestroyForm(route, blockedRoute => {
                core.errorStore.addError({
                    severity: 'warning',
                    component: 'DestroyModal',
                    action: 'submitDestroyForm',
                    type: 'authorization',
                    message: `DestroyModal: cross-origin route blocked (CSRF-token protection): ${blockedRoute}`,
                });
            });
        };

        return () => {
            const labels = core.config.labels;

            return h(
                'div',
                {
                    ref: modalRef,
                    class: 'modal fade',
                    id: MODAL_ID,
                    tabindex: -1,
                    'aria-labelledby': MODAL_LABEL_ID,
                    'aria-hidden': 'true',
                    'data-testid': 'destroy-modal',
                },
                [
                    h('div', { class: 'modal-dialog' }, [
                        h('div', { class: 'modal-content' }, [
                            h('div', { class: 'modal-header' }, [
                                h(
                                    'h5',
                                    { class: 'modal-title', id: MODAL_LABEL_ID },
                                    labels.confirmDeleteTitle
                                ),
                                h('button', {
                                    type: 'button',
                                    class: 'btn-close',
                                    'data-bs-dismiss': 'modal',
                                    'aria-label': labels.cancel,
                                }),
                            ]),
                            h('div', { class: 'modal-body' }, labels.confirmDeleteBody),
                            h('div', { class: 'modal-footer' }, [
                                h(
                                    'button',
                                    {
                                        type: 'button',
                                        class: 'btn btn-secondary',
                                        'data-bs-dismiss': 'modal',
                                    },
                                    labels.cancel
                                ),
                                h(
                                    'button',
                                    {
                                        type: 'button',
                                        class: 'btn btn-danger',
                                        onClick: handleConfirm,
                                    },
                                    labels.confirmDelete
                                ),
                            ]),
                        ]),
                    ]),
                ]
            );
        };
    },
});
